import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const log = await readFile(new URL('../log.html', import.meta.url), 'utf8');
const agents = await readFile(new URL('../AGENTS.md', import.meta.url), 'utf8');
const build = await readFile(new URL('../build.mjs', import.meta.url), 'utf8');

test('差分ログは不要な説明・対象ページ一覧・画面内ルールを表示しない', () => {
  assert.doesNotMatch(log, /PIXELMAP \/ CHANGE RECORD/);
  assert.doesNotMatch(log, /<h1>本番／test 差分ログ<\/h1>/);
  assert.doesNotMatch(log, /id="pages-title"/);
  assert.doesNotMatch(log, /class="page-list"/);
  assert.doesNotMatch(log, /id="rules-title"/);
  assert.doesNotMatch(log, /class="rules"/);
});

test('差分ログは現行のcell描画契約と主要な変更履歴を記載する', () => {
  assert.match(log, /\?render=cell2/);
  assert.match(log, /\?render=cell3/);
  assert.match(log, /3×3論理pxの単色セル/);
  assert.match(log, /神奈川県の生成GeoJSON/);
  assert.match(log, /production-comparison-z14/);
  assert.match(log, /retro-jrpg-z14/);
  assert.match(log, /本番copy profileで描画差をレイヤー別に収束/);
  assert.match(log, /BuildingSkin／RoadSkin／RailSkin／PoiPack/);
  assert.match(log, /水面・公園・スポーツ面をsurface familyへ分離/);
  assert.match(log, /generic fallbackを明示allowlistで監査/);
  assert.match(log, /z14固定/);
  assert.match(log, /2マップは位置同期/);
  assert.match(log, /既存のRPG風S／M／L施設スプライト/);
  assert.match(log, /facility-resolver/);
  assert.match(log, /WorldStyleでz14 POCのレトロJRPG表現を固定/);
  assert.match(log, /Asset Contractと共通描画基盤を正本化/);
  assert.match(log, /全7 iframe/);
  assert.match(log, /既存POIアセット描画を復旧/);
  assert.match(log, /不変ジオメトリ基準の統一Style Specを導入/);
  assert.match(log, /建物型施設アイコンの道路回避を取り消し/);
  assert.match(log, /ログページの表示内容を簡素化/);
  assert.match(log, /cell2を全ページの既定にしてcell3切替を追加/);
  assert.match(log, /<strong>全てに反映<\/strong>/);
  assert.match(log, /1マップ（<code>index\.html<\/code>）/);
  assert.match(log, /2マップ（<code>compare\.html<\/code>）/);
  assert.match(log, /4マップ（<code>four-maps\.html<\/code>/);
  assert.match(log, /standard、cell8、未知値を<code>cell2<\/code>へ正規化/);
  assert.match(log, /standalone設定を閉じて地図を全画面化/);
  assert.match(log, /設定パネルは初期状態で最小化し、右上の「＋／－」で開閉/);
  assert.match(log, /<strong>testのみ<\/strong>。standalone testで有効/);
  assert.match(log, /本番1・2・4マップの表示・設定UI・同期処理は変更なし/);
  assert.match(log, /設定ボタンを＋／－だけの右上固定へ変更/);
  assert.match(log, /設定の開閉状態にかかわらず同じ右上位置へ固定/);
  assert.match(log, /施設アイコンを収集ランドマークの建物表示へ限定/);
  assert.match(log, /事前収集ランドマークだけへ限定/);
  assert.match(log, /「たてもの」と同じ屋根・壁・影の描画器/);
  assert.match(log, /地区幹線道路の中央線を道路境界の中点へ整列/);
  assert.match(log, /両側境界の中点を挟む原子セル/);
  assert.match(log, /本番1・2・4マップは<code>!EMBEDDED<\/code> guardの対象外/);
  assert.match(log, /地区幹線道路の中央線を非表示/);
  assert.match(log, /道路の外縁色と路面色は維持/);
  assert.match(log, /従来の中央線を維持/);
  assert.match(log, /ランドマーク収集を5,000㎡以上へ拡張/);
  assert.match(log, /業務・商業ランドマーク/);
  assert.match(log, /building=commercial/);
  assert.match(log, /landuse=commercial/);
  assert.match(log, /ランドマーク下限を3,000㎡へ変更し公園・神社仏閣を追加/);
  assert.match(log, /ランドマーク収集下限を2,000㎡へ変更/);
  assert.match(log, /1,000㎡以上の施設敷地を意味タグから汎用収集/);
  assert.match(log, /汎用施設を選択だけでなく敷地面として確実に描画/);
  assert.match(log, /収集形状を必ず先に描き、その上へ敷地内のMVT建物を重ねる/);
  assert.match(log, /施設名ラベルは引き続き表示しない/);
  assert.match(log, /親施設20,169件/);
  assert.match(log, /汎用施設13,562件/);
  assert.match(log, /川崎変電所48,571㎡/);
  assert.match(log, /汎用施設ラベルは表示しない/);
  assert.match(log, /開いたwayは強制的に閉じず/);
  assert.match(log, /JR川崎タワー 商業棟/);
  assert.match(log, /leisure=park/);
  assert.match(log, /landuse=religious/);
  assert.match(log, /amenity=place_of_worship/);
  assert.match(log, /敷地全体を建物化せず施設記号/);
  assert.match(log, /現在のtestをWeb本番1・2・4マップへ全面リリース/);
  assert.match(log, /本番1・2・4マップの地図描画と施設データを現在のtest既定状態へ統一/);
  assert.match(log, /standalone・1・2・4マップの描画契約/);
  assert.match(log, /固定消失点とコンパス回転をWeb本番1・2・4マップへリリース/);
  assert.match(log, /2マップは位置と表示方位/);
  assert.match(log, /4マップは各地点を維持して同期表示方位だけを共有/);
  assert.match(log, /iframeやページを再読込しない/);
  assert.match(log, /全自動テスト155件/);
  assert.match(log, /建物の構造輪郭を素材感を保ったまま連続化/);
  assert.match(log, /平面建物の側面輪郭で3行に1行空けていた箇所/);
  assert.match(log, /standalone testのcell2／cell3建物描画/);
  assert.match(log, /平面・高さ建物の構造輪郭を連続させる/);
  assert.match(log, /全自動テスト156件/);
  assert.match(log, /黒い太帯化や立体感の消失がない/);
  assert.match(log, /建物の高さ表現を画面垂直押し出しへ変更/);
  assert.match(log, /接地位置から画面上方向だけへ持ち上げる/);
  assert.match(log, /standalone testのcell2／cell3建物描画/);
  assert.match(log, /本番1・2・4マップは固定消失点/);
  assert.match(log, /全自動テスト157件/);
  assert.match(log, /独立視覚レビューで4枚すべてPASS/);
  assert.match(log, /画面垂直の建物高さ表現をWeb本番へリリース/);
  assert.match(log, /固定消失点と高さ比例の横移動を外し/);
  assert.match(log, /standalone test（<code>variants\/map-02-refined\.html<\/code>）/);
  assert.match(log, /1マップ（<code>index\.html<\/code>）/);
  assert.match(log, /2マップ（<code>compare\.html<\/code>）/);
  assert.match(log, /4マップ（<code>four-maps\.html<\/code>／<code>variants\/height-stack-four-map\.html<\/code>）/);
  assert.match(log, /本番1・2・4マップの建物高さ線、壁面、影、構造輪郭がtestと同じ描画/);
  assert.match(log, /各iframeの版指定を更新/);
  assert.match(log, /本番1マップをcell2の0°・45°、2マップをcell2の45°、4マップをcell3の45°で撮影/);
  assert.match(log, /独立視覚レビューで本番用4枚すべてPASS/);
  assert.match(log, /4マップの方位・cell3同期、外側UIに回帰がない/);
  assert.match(log, /線路単位の連続レール描画をstandalone testへ導入/);
  assert.match(log, /左右別々の4連結経路を生成/);
  assert.match(log, /全体が並走し両端も近い線路だけは鉄道表示代表へ間引く/);
  assert.match(log, /交差・分岐と元の線路データは統合・削除しない/);
  assert.match(log, /standalone testのcell2／cell3における地上鉄道/);
  assert.match(log, /本番1・2・4マップは従来の中心セルごとの縦横判定/);
  assert.match(log, /全自動テスト158件/);
  assert.match(log, /独立視覚レビューは3枚すべてPASS/);
  assert.match(log, /黒い太帯・過密化・分岐消失/);
  assert.match(log, /現在のtest差分をWeb本番1・2・4マップへ全面リリース/);
  assert.match(log, /線路単位4連結レール・40論理px描画と5論理px空白・枕木なし/);
  assert.match(log, /宗教点データの<code>standalone_only<\/code>指定も生成スクリプトと生成GeoJSONから撤去/);
  assert.match(log, /4マップは外側の共通設定から7種類を4地点へ同期/);
  assert.match(log, /本番1・2・4マップの地図描画と施設データを2026-08-29時点のtest既定状態へ統一/);
  assert.match(log, /全自動テスト172件とビルドが成功/);
  assert.match(log, /最新スクリーンショット5枚は独立視覚レビューですべてPASS/);
  assert.match(log, /曇天の生活工業都市スキンをstandalone testへ追加/);
  assert.match(log, /weathered-industrial-day-z14/);
  assert.match(log, /サービスデッキ、タンク、煙突、ダクト/);
  assert.match(log, /元の道路中心線・建物footprint・水域境界を変更しない/);
  assert.match(log, /<strong>testのみ<\/strong>。URLを直接開いた<code>variants\/map-02-refined\.html<\/code>のcell2／cell3/);
  assert.match(log, /本番1・2・4マップは従来の<code>standard-pixel-art<\/code>/);
  assert.match(log, /最新スクリーンショット3枚は独立視覚レビューですべてPASS/);
  assert.match(log, /強度3のスチームパンク機械都市と大型ピクセル素材をstandalone testへ追加/);
  assert.match(log, /steampunk-megacity-day-z14/);
  assert.match(log, /ボイラー煙突、ガスホルダー、歯車塔、給水塔、配管束/);
  assert.match(log, /管橋、バルブ施設、鉄道ガントリー、冷却排出口/);
  assert.match(log, /機械素材1,692基・機械セル114,629・蒸気8,759/);
  assert.match(log, /宗教建物への誤蒸気は0件/);
  assert.match(log, /元の道路中心線・鉄道・建物footprint・水域境界は変更せず/);
  assert.match(log, /本番1・2・4マップは従来の<code>standard-pixel-art<\/code>とUI・同期処理を維持/);
});

test('AGENTSはtest変更とログ更新を同じ変更の完了条件にする', () => {
  assert.match(agents, /Any change to `variants\/map-02-refined\.html`[\s\S]*must update `log\.html` in the same change/);
  assert.match(agents, /JST date, change summary, affected mode, production impact, and verification/);
  assert.match(agents, /`testのみ`/);
  assert.match(agents, /`全てに反映`/);
  assert.match(agents, /incomplete until its `log\.html` entry/);
});

test('AGENTSは視覚修正後の撮影とサブエージェント確認を完了条件にする', () => {
  assert.match(agents, /After every visual map fix, capture a screenshot/);
  assert.match(agents, /delegate an independent visual review to a sub-agent/);
  assert.match(agents, /continue fixing, capture a new screenshot, and repeat/);
  assert.match(agents, /Do not deploy or report completion until the latest screenshot passes/);
});

test('ビルド成果物の公開対象に差分ログを含める', () => {
  assert.match(build, /'log\.html'/);
});
